// Copies the pure game engine out of purrfect-match/index.html into
// src/engine.gen.js, so the Worker checks scores with exactly the rules the
// game was played with. Wrangler runs this before every build (see
// wrangler.toml); tests import extractEngine() directly.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Must match engineVersion() in the game: FNV-1a over the engine's source.
export function fnv1a(str) {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(16).padStart(8, '0');
}

export function extractEngine(html) {
  const m = html.match(/<script id="purr-engine">([\s\S]*?)<\/script>/);
  if (!m) throw new Error('No <script id="purr-engine"> in the game page');
  const source = m[1].replace(/\r\n/g, '\n');
  return { source, version: fnv1a(source) };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const html = readFileSync(new URL('../purrfect-match/index.html', import.meta.url), 'utf8');
  const { source, version } = extractEngine(html);
  writeFileSync(
    new URL('./src/engine.gen.js', import.meta.url),
    '// Generated by build-engine.mjs from purrfect-match/index.html. Do not edit.\n' +
      source +
      '\nexport const ENGINE = globalThis.PurrEngine;\n' +
      `export const ENGINE_VERSION = ${JSON.stringify(version)};\n`
  );
  console.log(`engine ${version} -> src/engine.gen.js`);
}
